name: marketing-deploy

on:
  push:
    branches:
      - main
    paths:
      # this tells github to run this action only if anything changes under this directory
      - 'react-mfe-example/marketing/**'

defaults:
  run:
    # this specifies where the commands will run from
    working-directory: react-mfe-example/marketing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install
        run: npm Install

      - name: Build
        run: npm run build

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Sync aws folders
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/marketing/latest
     
      - name: Invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/marketing/latest/remoteEntry.js"
